--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/HmmHmmmm/GameEventPlugin
build-by-default: true
branches:
- master
projects:
  GameEventPlugin:
    path: ""
    icon: "images/icon.png"
    libs:
    - src: xenialdan\customui\customui
      version: 3.0.0
...
