name: GameEventPlugin
version: 3.1
api: 3.11.0
author: HmmHmmmmm
main: hmmhmmmm\gameevent\GameEvent
website: https://github.com/HmmHmmmm/GameEventPlugin
depend:
- Slapper

permissions:
  gameevent:
    default: false
    children:
      gameevent.command:
        default: op